### ISSUE TITLE
Can add qca-ovsmgr packages?

### ISSUE THREAD

**Issue by zxlhhyccc** [qosmio/nss-packages#17]

**Comment by qosmio** [comment]
You can test branch https://github.com/qosmio/nss-packages/tree/NSS-12.4-K6.1-ovs. You'll need to build with ovs branch here https://github.com/qosmio/openwrt-ipq/tree/qualcommax-6.1-nss-wifi-ovs.

It compiles and loads. But since I don't use it. I won't be supporting it. That should at least let you test.
