### ISSUE TITLE
qca-nss-drv failed to build

### ISSUE THREAD

**Issue by chanrio13** [qosmio/nss-packages#34]
Hi, 
Im creating an image for Arcadyan AW1000 with ipq807x. Im getting an error of failed to build for qca-nss-drv. I tried changing fron 11.4 - 12.5 to no avail. Same issue.

**Comment by qosmio** [comment]
I can’t help you troubleshoot without more details. I need the full build error output, not just a summary of the error. Also, what environment are you building this on? Have you made any custom changes?

**Comment by leideno** [comment]
I believe this is due to the '0018-ecm-limit-fw-12.2.patch' being removed in a commit some time ago, the build fails due to 'NSS_IPV4_RULE_CREATE_RAWIP_VALID' being undeclared in NSS Firmware < 12.5
[0018-ecm-limit-fw-12.2.tar.gz](https://github.com/user-attachments/files/17110079/0018-ecm-limit-fw-12.2.tar.gz)

**Comment by chanrio13** [comment]
Hello you may close this item. Im able to get it working using your repo. I was using different repo during the build
